AdminUI/Models/ErrorViewModel.cs
namespace AdminUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdminUI/Models/UsersModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminUI.Models
{
    public class UsersModel
    {
        public int UsersId { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        public string? LastName { get; set; }
        [Required]
        public string? Email { get; set; }
        [Required]
        public string? Password { get; set; }
        [Required]
        public bool RestoreUser { get; set; }
        [Required]
        public bool Active { get; set; }
    }
}

AdminUI/Controllers/HomeController.cs
using AdminUI.Data;
using AdminUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdminUI.Controllers
{
    public class HomeController : Controller
    {
        public UsersData usersData = new UsersData();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Users()
        {
            return View();
            
        }

        [HttpGet]

        public async Task<JsonResult> ListUsers()
        {
            var users =await usersData.ListUsers();

            return Json(new {data=users});
        }

        public IActionResult RegisterNewUser()
        {
            return View();
        }
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdminUI/Controllers/MaintainerController.cs
using Microsoft.AspNetCore.Mvc;

namespace AdminUI.Controllers
{
    public class MaintainerController : Controller
    {
        public IActionResult Categories()
        {
            return View();
        }
        public IActionResult Brands()
        {
            return View();
        }
        public IActionResult Products()
        {
            return View();
        }
    }
}

AdminUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

AdminUI/Views/Home/RegisterNewUser.cshtml
@model UsersModel;
@{
    ViewData["Title"] = "RegisterNewUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

AdminUI/Views/Home/Users.cshtml
@model List<UsersModel>;
@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Resumen</a></li>
    <li class="breadcrumb-item active">Usuarios</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i> Control de usuarios
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button class="btn btn-success" onclick="OpenUserModal(null)">Agregar nuevo usuario</button>
            </div>
        </div>
        <hr />
        <table class="display cell-border" id="table" style="width:100%">
            <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Correo</th>
                    <th scope="col">Activo</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="NewUserModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Usuarios</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @* Form starts here *@
                
                     <input hidden id="UserId" value=0/>

                    <div class="row">
                    <div class="mb-3 col-sm-6">
                        <label for="NewUserName" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="NewUserName">
                    </div>
                    <div class="mb-3 col-sm-6">
                        <label for="newUserLastname" class="form-label">Apellido</label>
                        <input type="text" class="form-control" id="NewUserLastname">
                    </div>
                    <div class="mb-3 col-sm-6">
                        <label for="newUserEmail" class="form-label">Email</label>
                            <input type="email" class="form-control" id="NewUserEmail">
                    </div> 

                    <div class="col-sm-6">
                    <label for="isActive" class="form-label">Activo</label>
                    <select id="isActive">

                        <option value=1>Sí</option>
                        <option value=0>No</option>
                    </select>
                    </div>
                    </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar
                </button>
                <button type="button" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        var tableData;

        tableData = $('#table').DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListUsers", "Home")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                { "data": "name" },
                { "data": "lastName" },
                { "data": "email" },
                {
                    "data": "active", "render": (value) => {
                        if (value) {
                            return '<span class="badge bg-success">Sí</span>';
                        } else {
                            return '<span class="badge bg-danger">No</span>';
                        }
                    }
                }, {
                    "defaultContent": '<a class="btn btn-sm btn-warning btn-edit"><i class="fas fa-pen"></i></a>'+
                        '<a class="btn btn-sm btn-danger ms-2" asp-controller="" asp-action=""><i class="fas fa-trash"></i></a>',
                             "orderable": false,
                             "searchable":false,
                             "width":"90px"
                }
            ],
            "language": { 
                "url": "https://cdn.datatables.net/plug-ins/2.0.8/i18n/es-MX.json" 
            }
                });

        function OpenUserModal(json){
                $('#NewUserName').val("");
                $('#NewUserLastname').val("");
                $('#NewUserEmail').val("");
                $('#isActive').val(0);

            if (json != null) {
                $('#NewUserName').val(json.name);
                $('#NewUserLastname').val(json.lastName);
                $('#NewUserEmail').val(json.email);
                    $('#isActive').val(json.active == true ? 1 : 0);
            }
                
                $('#NewUserModal').modal("show");           

        }

        $('#table tbody').on('click', '.btn-edit', function () {
            
            var selectedRow = $(this).closest('tr');

            var data = tableData.row(selectedRow).data();

            console.log(data);
            OpenUserModal(data);
        });

        function SaveUser() {
                var userData = {
                    active: $('#isActive').val() == 1 ? true : false,
                    email: $('#NewUserEmail').val(),
                    lastName: $('#NewUserLastname').val(),
                    name: $('#NewUserName').val(""),
                    usersId: $("#UserId").val()
                    }
        }
    </script>
}

AdminUI/Views/Maintainer/Brands.cshtml
@{
    ViewData["Title"] = "Brands";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Brands</h1>

AdminUI/Views/Maintainer/Categories.cshtml
@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Categories</h1>

AdminUI/Views/Maintainer/Products.cshtml
@{
    ViewData["Title"] = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Products</h1>

AdminUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/jquery.dataTables.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/responsive.dataTables.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

</head>
<body class="sb-nav-fixed">
    
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">ECommerceApp</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo de usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar sesión</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">RESUMEN</div>
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a><a class="nav-link" asp-controller="Home" asp-action="Users">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Usuarios
                        </a>
                        
                        <div class="sb-sidenav-menu-heading">MANTENIMIENTO</div>
                        <a class="nav-link" asp-controller="Maintainer" asp-action="Categories">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Categorias
                        </a>
                        <a class="nav-link" asp-controller="Maintainer" asp-action="Brands">
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Marcas
                        </a> 
                        <a class="nav-link" asp-controller="Maintainer" asp-action="Products">
                            <div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>
                            Productos
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="assets/demo/chart-pie-demo.js"></script> *@
    <script src="~/js/scripts.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/all.min.js"></script>
    <script src="~/js/jquery.dataTables.js"></script>
    <script src="~/js/dataTables.responsive.js"></script>

    
         
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>